# Generated by Django 4.0.2 on 2022-02-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_pytania', models.CharField(max_length=300)),
                ('data_publikacji', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_dpowiedzi', models.CharField(max_length=400)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ankieta.pytanie')),
            ],
        ),
    ]
